export const filterData = [
  { id: "1a2b3c", name: "Motorcycle", filterKey: "motorcycle" },
  { id: "4d5e6f", name: "Person", filterKey: "person" },
  { id: "7g8h9i", name: "Bicycle", filterKey: "bicycle" },
  { id: "0j1k2l", name: "Knife", filterKey: "knife" },
  { id: "3m4n5o", name: "Cake", filterKey: "cake" },
  { id: "6p7q8r", name: "Sink", filterKey: "sink" },
  { id: "9s0t1u", name: "Cow", filterKey: "cow" },
  { id: "2v3w4x", name: "Umbrella", filterKey: "umbrella" },
  { id: "5y6z7a", name: "Mouse", filterKey: "mouse" },
  { id: "8b9c0d", name: "Keyboard", filterKey: "keyboard" },
  { id: "1e2f3g", name: "Tv", filterKey: "tv" },
  { id: "4h5i6j", name: "Cat", filterKey: "cat" },
  { id: "7k8l9m", name: "Bottle", filterKey: "bottle" },
  { id: "0n1o2p", name: "Potted plant", filterKey: "potted plant" },
  { id: "3q4r5s", name: "Refrigerator", filterKey: "refrigerator" },
  { id: "6t7u8v", name: "Clock", filterKey: "clock" },
  { id: "9w0x1y", name: "Spoon", filterKey: "spoon" },
  { id: "2z3a4b", name: "Bowl", filterKey: "bowl" },
  { id: "5c6d7e", name: "Orange", filterKey: "orange" },
  { id: "8f9g0h", name: "Oven", filterKey: "oven" },
  { id: "1i2j3k", name: "Handbag", filterKey: "handbag" },
  { id: "4l5m6n", name: "Wine glass", filterKey: "wine glass" },
  { id: "7o8p9q", name: "Dining table", filterKey: "dining table" },
  { id: "0r1s2t", name: "Cup", filterKey: "cup" },
  { id: "3u4v5w", name: "Backpack", filterKey: "backpack" },
  { id: "6x7y8z", name: "Microwave", filterKey: "microwave" },
  { id: "9a0b1c", name: "Book", filterKey: "book" },
  { id: "2d3e4f", name: "Toaster", filterKey: "toaster" },
  { id: "5g6h7i", name: "Fork", filterKey: "fork" },
  { id: "8j9k0l", name: "Toilet", filterKey: "toilet" },
  { id: "1m2n3o", name: "Train", filterKey: "train" },
  { id: "4p5q6r", name: "Stop sign", filterKey: "stop sign" },
  { id: "7s8t9u", name: "Chair", filterKey: "chair" },
  { id: "0v1w2x", name: "Laptop", filterKey: "laptop" },
  { id: "3y4z5a", name: "Bench", filterKey: "bench" },
  { id: "6b7c8d", name: "Apple", filterKey: "apple" },
  { id: "9e0f1g", name: "Vase", filterKey: "vase" },
  { id: "2h3i4j", name: "Broccoli", filterKey: "broccoli" },
  { id: "5k6l7m", name: "Skateboard", filterKey: "skateboard" },
  { id: "8n9o0p", name: "Truck", filterKey: "truck" },
  { id: "1q2r3s", name: "Boat", filterKey: "boat" },
  { id: "4t5u6v", name: "Elephant", filterKey: "elephant" },
  { id: "7w8x9y", name: "Teddy bear", filterKey: "teddy bear" },
  { id: "0z1a2b", name: "Bird", filterKey: "bird" },
  { id: "3c4d5e", name: "Toothbrush", filterKey: "toothbrush" },
  { id: "6f7g8h", name: "Cell phone", filterKey: "cell phone" },
  { id: "9i0j1k", name: "Car", filterKey: "car" },
  { id: "2l3m4n", name: "Fire hydrant", filterKey: "fire hydrant" },
  { id: "5o6p7q", name: "Dog", filterKey: "dog" },
  { id: "8r9s0t", name: "Traffic light", filterKey: "traffic light" },
  { id: "1u2v3w", name: "Bus", filterKey: "bus" },
  { id: "4x5y6z", name: "Parking meter", filterKey: "parking meter" },
  { id: "7a8b9c", name: "Donut", filterKey: "donut" },
  { id: "0d1e2f", name: "Airplane", filterKey: "airplane" },
  { id: "3g4h5i", name: "Tie", filterKey: "tie" },
  { id: "6j7k8l", name: "Surfboard", filterKey: "surfboard" },
  { id: "9m0n1o", name: "Banana", filterKey: "banana" },
  { id: "2p3q4r", name: "Horse", filterKey: "horse" },
  { id: "5s6t7u", name: "Remote", filterKey: "remote" },
  { id: "8v9w0x", name: "Giraffe", filterKey: "giraffe" },
  { id: "1y2z3a", name: "Sheep", filterKey: "sheep" },
  { id: "4b5c6d", name: "Zebra", filterKey: "zebra" },
  { id: "7e8f9g", name: "Snowboard", filterKey: "snowboard" },
  { id: "0h1i2j", name: "Couch", filterKey: "couch" },
  { id: "3k4l5m", name: "Suitcase", filterKey: "suitcase" },
  { id: "6n7o8p", name: "Bed", filterKey: "bed" },
  { id: "9q0r1s", name: "Sports ball", filterKey: "sports ball" },
  { id: "2t3u4v", name: "Hair drier", filterKey: "hair drier" },
  { id: "5w6x7y", name: "Frisbee", filterKey: "frisbee" },
  { id: "8z9a0b", name: "Bear", filterKey: "bear" },
  { id: "1c2d3e", name: "Hot dog", filterKey: "hot dog" },
  { id: "4f5g6h", name: "Baseball bat", filterKey: "baseball bat" },
  { id: "7i8j9k", name: "Baseball glove", filterKey: "baseball glove" },
  { id: "0l1m2n", name: "Skis", filterKey: "skis" },
  { id: "3o4p5q", name: "Pizza", filterKey: "pizza" },
  { id: "6r7s8t", name: "Carrot", filterKey: "carrot" },
  { id: "9u0v1w", name: "Sandwich", filterKey: "sandwich" },
  { id: "2x3y4z", name: "Tennis racket", filterKey: "tennis racket" },
  { id: "5a6b7c", name: "Kite", filterKey: "kite" },
  { id: "8d9e0f", name: "Scissors", filterKey: "scissors" },
];
